services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    restart: on-failure

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    restart: always

  import_fake_data:
    image: mongo
    depends_on:
      - mongodb
    restart: on-failure
    volumes:
      - ./database/init.json:/init.json
    command: mongoimport --host mongodb --username ${MONGO_USERNAME} --password ${MONGO_PASSWORD} --db default --collection user --type json --file /init.json --jsonArray --authenticationDatabase=admin