FROM mongo

CMD mongoimport --host mongodb --username root --password IZyCTpT1z7sBK8JbG6s3XkZDT9iIgP5Zf2wW9F3LmUD6JW7E7LfSsfZfGWHWOIbl --db default --collection user --type json --file /init.json --jsonArray --authenticationDatabase=admin